version: '3.9'

services:
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
#      - ./src:/var/www/html
      - ./symfony:/var/www/symfony/
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: .
    container_name: php-fpm
    image: php:8.1-fpm
    volumes:
#      - ./src:/var/www/html
      - ./symfony:/var/www/symfony

  postgres:
    container_name: postgres_container
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: /var/www/html/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      -  ./pgdata:/var/www/html/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.6
    environment:
      PGADMIN_DEFAULT_EMAIL: "mikulenokvlad@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
      PGADMIN_CONFIG_SERVER_MODE: "False"
      GADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:80"
    restart: unless-stopped
